version: '3.7'

services:
  app:
    image: chaosdorf/pawebcontrol:latest
    environment:
      - PULSE_SERVER=pulse.chaosdorf.space
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 60s
        max_attempts: 5
      update_config:
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.125'
          memory: 4M
      labels:
        - traefik.swarm.network=traefik_net
        - traefik.http.services.pulseweb.loadbalancer.server.port=8000
        - "traefik.http.routers.pulseweb-http.rule=Host(`pulseweb.chaosdorf.space`) || Host(`pulseweb`)"
        - traefik.http.routers.pulseweb-http.middlewares=global-headers@file,pulseweb-error@swarm
        - traefik.http.routers.pulseweb-http.service=pulseweb@swarm
        - "traefik.http.routers.pulseweb-https.rule=Host(`pulseweb.chaosdorf.space`) || Host(`pulseweb`)"
        - traefik.http.routers.pulseweb-https.middlewares=global-headers@file,pulseweb-error@swarm
        - traefik.http.routers.pulseweb-https.service=pulseweb@swarm
        - traefik.http.routers.pulseweb-https.tls=true
        - traefik.http.routers.pulseweb-https.tls.certresolver=default
        - traefik.http.routers.pulseweb-https.tls.domains[0].main=*.chaosdorf.space
        - traefik.http.middlewares.pulseweb-error.errors.service=error@swarm
        - traefik.http.middlewares.pulseweb-error.errors.status=401,403,404,429,500,503
        - traefik.http.middlewares.pulseweb-error.errors.query=/{status}.html

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net
